services:
  semantickernelaiagentbackend:
    image: semantickernel-aiagentbackend
    container_name: semantickernelaiagentbackend
    build:
      context: ./backend/SemanticKernel.AIAgentBackend
      dockerfile: SemanticKernel.AIAgentBackend/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__AppDBConnectionString=Server=agenticaisqlserver,1433;Database=AgenticAIDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - qdrant
      - blobstorage
      - agenticaisqlserver
    networks:
      - app_network

  aiagent-client:
    image: aiagent-client
    container_name: aiagentclient
    build:
      context: ./frontend/ai-agent
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - semantickernelaiagentbackend
    networks:
      - app_network

  agenticaisqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: agenticaisqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - app_network

  qdrant:
    image: qdrant/qdrant:v1.12.4
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"   # HTTP API
      - "6334:6334"   # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app_network

  blobstorage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: blobstorage
    restart: always
    ports:
      - "10000:10000"   # Blob Storage
    volumes:
      - blobstorage_data:/data
    networks:
      - app_network
    command: "azurite --blobHost 0.0.0.0 --loose --skipApiVersionCheck"

volumes:
  sqlserverdata:
    driver: local
  qdrant_data:
    driver: local
  blobstorage_data:
    driver: local

networks:
  app_network:
    driver: bridge