version: '3.4'

services:
  semantickernel.aiagentbackend:
    image: ${DOCKER_REGISTRY-}semantickernelaiagentbackend
    build:
      context: .
      dockerfile: SemanticKernel.AIAgentBackend/Dockerfile
    environment:
      - ConnectionStrings__AppDBConnectionString=Server=agenticaisqlserver,1433;Database=AgenticAIDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - qdrant
      - blobstorage
      - agenticaisqlserver
      - ffmpeg-node
      - docx-pdf-service
    networks:
      - app_network

  agenticaisqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: agenticaisqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - app_network

  qdrant:
    image: qdrant/qdrant:v1.12.4
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"   # HTTP API
      - "6334:6334"   # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app_network

  blobstorage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: blobstorage
    restart: always
    ports:
      - "10000:10000"   # Blob Storage
    volumes:
      - blobstorage_data:/workspace
    networks:
      - app_network
    command: "azurite --blobHost 0.0.0.0 --loose --skipApiVersionCheck --location /workspace"

  ffmpeg-node:
    build:
     context:  ../../ffmpeg-node-service
    container_name: ffmpeg-node
    volumes:
      - ffmpeg_data:/ffmpeg_data
    ports:
      - "5001:5000"
    networks:
      - app_network

  docx-pdf-service:
    build:
     context:  ../../docx-to-pdf-node-service
    container_name: docx-pdf-service
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
     - docx_uploads:/app/uploads
     - docx_outputs:/app/outputs


volumes:
  sqlserverdata:
    driver: local
  qdrant_data:
    driver: local
  blobstorage_data:
    driver: local
  ffmpeg_data:
    driver: local
  docx_uploads:
   driver: local
  docx_outputs:
    driver: local

networks:
  app_network:
    driver: bridge